=== UrbilArri/sza/html/abisuak.dtd
<!ELEMENT abisuak (abisua)*>
<!ATTLIST abisuak azkenid IDREF #REQUIRED>
<!ELEMENT abisua (data, mota, pribintzia, hiria, errepidea, iruzkina)>
<!ATTLIST abisua id ID #REQUIRED>
<!ELEMENT data (#PCDATA)>
<!ELEMENT mota (#PCDATA)>
<!ELEMENT probintzia (#PCDATA)>
<!ELEMENT hiria (#PCDATA)>
<!ELEMENT errepidea (#PCDATA)>
<!ELEMENT iruzkina (#PCDATA)>

=== UrbilArri/sza/html/abisuak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "abisuak.dtd">
<abisuak><abisua id="n0"><data>12/04/2017 05:55:17 pm</data><mota>Istripua</mota><probintzia>Bizkaia</probintzia><hiria>irun</hiria><errepidea>n-1</errepidea><iruzkina>oso arazo larriak&#13;
</iruzkina></abisua><abisua id="n1"><data>12/04/2017 05:55:52 pm</data><mota>Istripua</mota><probintzia>Bizkaia</probintzia><hiria>irun</hiria><errepidea>n-1</errepidea><iruzkina>oso arazo larriak&#13;
</iruzkina></abisua></abisuak>
