=== UrbilArri/sza/dtd/erabiltzailea.dtd
<!ELEMENT erabiltzaileak (erabiltzailea)*>
<!ELEMENT erabiltzailea (izena, abizena, korreoa, hiria, erabiltzailea, pasahitza)>
<!ATTLIST erabiltzailea id ID #REQUIRED>
<!ELEMENT izena (#PCDATA)>
<!ELEMENT abizena (#PCDATA)>
<!ELEMENT korreoa (#PCDATA)>
<!ELEMENT hiria (#PCDATA)>
<!ELEMENT erabiltzailea (#PCDATA)>
<!ELEMENT pasahitza (#PCDATA)>

=== UrbilArri/sza/xml/erabiltzaileak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "../dtd/erabiltzailea.dtd">
<erabiltzaileak>
<erabiltzailea id="n0"><izena>jokin</izena><abizena>garmendia</abizena><korreoa>jokin@garmendia.eus</korreoa><hiria>tolosa</hiria><erab>Joakin</erab><pasahitza>pasahitza</pasahitza></erabiltzailea><erabiltzailea id="n1"><izena>urbil</izena><abizena>arribillaga</abizena><korreoa>urbil@arribillaga.eus</korreoa><hiria>Irun</hiria><erab>Urbil</erab><pasahitza>pasahitza</pasahitza></erabiltzailea></erabiltzaileak>
